<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePaymentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
    */
    public function up()
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('order_id')
                ->comment('Relation with your order table');

            $table->double('payable_amount', [12,2])
                ->default(0.00)
                ->comment('An amount you request to pay to customer');

            $table->string('transaction_id')
                ->unique()
                ->comment('An unique id generated by your system for refernce both you and sslcommerz');

            $table->string('session_key', 191)
                ->nullable();

            $table->string('payment_method')
                ->nullable();

            $table->string('payment_gateway')
                ->nullable();

            $table->string('bank_transaction_id')
                ->nullable()
                ->comment('Bank transaction id which provided by sslcommerz for reference');

            $table->string('account_no')
                ->nullable();

            $table->double('actual_paid_amount', [12,2])->default(0.00)
                ->comment('An amount customer paid to sslcommerz');

            $table->double('store_amount', [12,2])
                ->default(0)
                ->comment('Amount after deduction of payment gateway fees');

            $table->enum('currency', ['BDT', 'USD'])
                ->default('BDT');

            $table->tinyInteger('status')
                ->default(0)
                ->comment('0 = pending, 1 = success, 2 = verified, 7 = failed, 9 = canceled');

            $table->timestamps(); //for time references
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('payments');
    }
}
